kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: fajar4561/aosp-builder:latest
   environment:
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     TG_TOKEN:
       from_secret: TG_TOKEN
     AWAL:
       from_secret: AWAL
     AKHIR:
       from_secret: AKHIR
   commands:
      - git config --global user.name "$AWAL"
      - git config --global user.email "maulanafajar751@gmail.com"
      - git clone --depth=1 https://$AWAL:$AKHIR@github.com/fajar4561/Kernel_Asus_SDM660 -b eas kernel && cd kernel
      - curl https://raw.githubusercontent.com/fajar4561/Android-Kernel-builder/main/build.sh > run.sh
      - bash run.sh